### ISSUE TITLE
ファビコンを設定する

### ISSUE THREAD

**Issue by kkazuki0312** [kkazuki0312/my-site#7]

**Comment by tomokun1210** [comment]
<img width="257" alt="スクリーンショット 2020-01-22 19 30 32" src="https://user-images.githubusercontent.com/60177736/72886745-b49a2b00-3d4d-11ea-8d4b-27960bd756f3.png">

**Comment by kkazuki0312** [comment]
ともくんをアサインしました

**Comment by kkazuki0312** [comment]
対応完了しました
